fix(aws): manually triggering codedeploy orb

diff --git a/.circleci/common.yml b/.circleci/common.yml
--- a/.circleci/common.yml
+++ b/.circleci/common.yml
@@ -1,7 +1,7 @@
 version: 2.1
 
 orbs:
-  aws-cli: circleci/aws-cli@2.0.6
+  aws-cli: circleci/aws-cli@4.1.3
   aws-ecr: circleci/aws-ecr@7.3.0
   aws-code-deploy: circleci/aws-code-deploy@3.0.0
   aws-ecs: circleci/aws-ecs@4.0.0
@@ -157,7 +157,7 @@ commands:
       - run: 
           name: Install and setup node
           command: |
-            . /home/circleci/.codebuild_shims_wrapper.sh
+            printenv
             nvm install
             nvm use
             npm install -g pnpm   
@@ -167,7 +167,6 @@ commands:
       - run: 
           name: Setup our secrets from AWS Secret Manager
           command: |
-            . /home/circleci/.codebuild_shims_wrapper.sh
             echo 'export SECRET_VALUE="$(aws secretsmanager get-secret-value --secret-id CodeBuild/Default --query SecretString --output text)"' >> "$BASH_ENV"
             echo 'export TERRAFORM_TOKEN="$(echo $SECRET_VALUE | jq -r '.terraform_token')"' >> "$BASH_ENV"
             echo 'export PAGERDUTY_TOKEN="$(echo $SECRET_VALUE | jq -r '.mozilla_pagerduty_token')"' >> "$BASH_ENV"
@@ -209,6 +208,7 @@ jobs:
       <<: [*repo_for_enum, *resource_class_enmum]
     # Our self hosted runners dont support docker images, cause its not deployed in kubernetes, so we have some special steps
     machine: true
+    shell: /bin/bash --login -eo pipefail
     resource_class: << parameters.resource-class >>
     steps:
       - exit-early-if-irrelevant:
@@ -236,7 +236,6 @@ jobs:
                   - run:
                       name: Build Dev Infra
                       command: |
-                        . /home/circleci/.codebuild_shims_wrapper.sh
                         nvm use
                         export NODE_ENV=development
                         pnpm run synth --filter=<< parameters.scope >>...
@@ -246,7 +245,6 @@ jobs:
                   - run:
                       name: Build Prod Infra
                       command: |
-                        . /home/circleci/.codebuild_shims_wrapper.sh
                         nvm use
                         export NODE_ENV=production
                         pnpm run synth --filter=<< parameters.scope >>...
@@ -272,34 +270,30 @@ jobs:
       - run:
           name: Setup terraform
           command: |
-            . /home/circleci/.codebuild_shims_wrapper.sh
             cd << parameters.stack-output-path >>
             tfenv use
             terraform init
       - when:
           condition: <<parameters.apply>>
           steps:
-            - attach_workspace:
-                at: /tmp/workspace
             - run:
                 name: Terraform apply
                 command: |
-                  . /home/circleci/.codebuild_shims_wrapper.sh
                   cd << parameters.stack-output-path >>
                   /home/circleci/tfcmt --var target:<< parameters.scope >><<#parameters.dev>>-dev<</parameters.dev>> apply -- terraform apply -auto-approve -lock-timeout=10m
-                  echo "TF_OUTPUT=$(terraform output -json)" >> $BASH_ENV
+                  mkdir -p /tmp/workspace
+                  echo "$(terraform output -json)" > /tmp/workspace/tf_output.json
             # Persist TF_OUTPUT using workspace
             - persist_to_workspace:
-                root: .
+                root: /tmp/workspace
                 paths:
-                  - $BASH_ENV
+                  - tf_output.json
       - unless:
           condition: <<parameters.apply>>
           steps:
             - run:
                 name: Terraform plan
                 command: |
-                  . /home/circleci/.codebuild_shims_wrapper.sh
                   cd << parameters.stack-output-path >>
                   /home/circleci/tfcmt --var target:<< parameters.scope >><<#parameters.dev>>-dev<</parameters.dev>> plan --skip-no-changes --patch -- terraform plan -lock-timeout=10m
       - save_cache:
@@ -323,35 +317,74 @@ jobs:
       <<: [*repo_for_enum, *resource_class_enmum]
     # Our self hosted runners dont support docker images, cause its not deployed in kubernetes, so we have some special steps
     machine: true
+    shell: /bin/bash --login -eo pipefail
     resource_class: << parameters.resource-class >>
     steps:
       - exit-early-if-irrelevant:
           for: << parameters.for >>
       # Restore TF_OUTPUT from workspace
       - attach_workspace:
-          at: .
+          at: /tmp/workspace
       - run:
           # Pulls out the terraform params needed for CodeDeploy and then re-saves them to be used in the CodeDeploy ORB
           name: CodeDeploy Load Env
           command: |
-            . /home/circleci/.codebuild_shims_wrapper.sh
-            source $BASH_ENV
-            ECS_TASK_ARN=$(echo $TF_OUTPUT | jq -r '.ecs-task-arn.value')
-            ECS_TASK_CONTAINER_NAME=$(echo $TF_OUTPUT | jq -r '.ecs-task-containerName.value')
-            ECS_TASK_CONTAINER_PORT=$(echo $TF_OUTPUT | jq -r '.ecs-task-containerPort.value')
+            TF_OUTPUT=$(cat /tmp/workspace/tf_output.json)
+            ECS_TASK_ARN=$(echo "$TF_OUTPUT" | jq -r '.["ecs-task-arn"].value')
+            ECS_TASK_CONTAINER_NAME=$(echo "$TF_OUTPUT" | jq -r '.["ecs-task-containerName"].value')
+            ECS_TASK_CONTAINER_PORT=$(echo "$TF_OUTPUT" | jq -r '.["ecs-task-containerPort"].value')
+            ECS_TASK_FAMILY=$(echo "$TF_OUTPUT" | jq -r '.["ecs-task-family"].value')
+            ECS_CODEDEPLOY_GROUP=$(echo "$TF_OUTPUT" | jq -r '.["ecs-codedeploy-group"].value')
+            ECS_CODEDEPLOY_APP=$(echo "$TF_OUTPUT" | jq -r '.["ecs-codedeploy-app"].value')
 
             echo "export ECS_TASK_ARN=$ECS_TASK_ARN" >> $BASH_ENV
             echo "export ECS_TASK_CONTAINER_NAME=$ECS_TASK_CONTAINER_NAME" >> $BASH_ENV
             echo "export ECS_TASK_CONTAINER_PORT=$ECS_TASK_CONTAINER_PORT" >> $BASH_ENV
-      - aws-ecs/update_service:
-          name: Deploy ECS Service
-          codedeploy_application_name: << parameters.codedeploy-app-name >>
-          codedeploy_deployment_group_name: << parameters.codedeploy-group-name >>
-          codedeploy_load_balanced_container_name: ${ECS_TASK_CONTAINER_NAME}
-          codedeploy_load_balanced_container_port: ${ECS_TASK_CONTAINER_PORT}
-          container_image_name_updates: tag=$CIRCLECI_SHA1, container=${ECS_TASK_CONTAINER_NAME}
-          deployment_controller: CODE_DEPLOY
-          verify_revision_is_deployed: true
+            echo "export ECS_TASK_FAMILY=$ECS_TASK_FAMILY" >> $BASH_ENV
+            echo "export ECS_CODEDEPLOY_GROUP=$ECS_CODEDEPLOY_GROUP" >> $BASH_ENV
+            echo "export ECS_CODEDEPLOY_APP=$ECS_CODEDEPLOY_APP" >> $BASH_ENV
+
+      ## All the following steps are copied from https://github.com/CircleCI-Public/aws-ecs-orb/blob/master/src/commands/update_service.yml but we manually run them so we can pass env variables that we otherwise couldn't since it relies on parameter steps.
+      ## See open issue to clean up when we can. https://github.com/CircleCI-Public/aws-ecs-orb/issues/211
+      ## Once the above issue is fixed we can remove the included script and these commands and replace it with the below.
+      # - aws-ecs/update_service:
+      #     name: Deploy ECS Service
+      #     codedeploy_application_name: ${ECS_CODEDEPLOY_APP}
+      #     codedeploy_deployment_group_name: ${ECS_CODEDEPLOY_GROUP}
+      #     codedeploy_load_balanced_container_name: ${ECS_TASK_CONTAINER_NAME}
+      #     codedeploy_load_balanced_container_port: ${ECS_TASK_CONTAINER_PORT}
+      #     family: ${ECS_TASK_FAMILY}
+      #     container_image_name_updates: tag=${CIRCLE_SHA1}, container=${ECS_TASK_CONTAINER_NAME}
+      #     deployment_controller: CODE_DEPLOY
+      #     verify_revision_is_deployed: true
+
+      - aws-cli/install
+      - run:
+          name: Setup AWS Auth
+          command: |
+            aws configure set profile.default.credential_source EcsContainer
+
+      - aws-ecs/update_task_definition:
+          family: ${ECS_TASK_FAMILY}
+          container_image_name_updates: tag=${CIRCLE_SHA1}, container=${ECS_TASK_CONTAINER_NAME}
+
+      - run:
+          name: Update ECS Blue/Green service with registered task definition.
+          command: \<< include(scripts/update_bluegreen_service_via_task_def.sh) >>
+          no_output_timeout: 10m
+          environment:
+            DEPLOYMENT_CONTROLLER: CODE_DEPLOY
+            ORB_STR_CD_APP_NAME: ${ECS_CODEDEPLOY_APP}
+            ORB_STR_CD_DEPLOY_GROUP_NAME: ${ECS_CODEDEPLOY_GROUP}
+            ORB_STR_CD_LOAD_BALANCED_CONTAINER_NAME: ${ECS_TASK_CONTAINER_NAME}
+            ORB_INT_CD_LOAD_BALANCED_CONTAINER_PORT:  ${ECS_TASK_CONTAINER_PORT}
+            ORB_BOOL_VERIFY_REV_DEPLOY: true
+            ORB_STR_PROFILE_NAME: default
+            ORB_BOOL_ENABLE_CIRCUIT_BREAKER: false
+            ORB_STR_CD_CAPACITY_PROVIDER_NAME: 
+            ORB_STR_CD_CAPACITY_PROVIDER_WEIGHT: 
+            ORB_STR_CD_CAPACITY_PROVIDER_BASE: 
+            ORB_STR_CD_DEPLOYMENT_CONFIG_NAME:
 
   code_deploy_lambda:
     parameters:
@@ -379,6 +412,7 @@ jobs:
       <<: [*repo_for_enum, *resource_class_enmum]
     # Our self hosted runners dont support docker images, cause its not deployed in kubernetes, so we have some special steps
     machine: true
+    shell: /bin/bash --login -eo pipefail
     resource_class: << parameters.resource-class >>
     steps:
       - exit-early-if-irrelevant:
@@ -386,7 +420,6 @@ jobs:
       - run:
           name: Deploy Lambda
           command: |
-            . /home/circleci/.codebuild_shims_wrapper.sh
             export AWS_PAGER=""
             aws lambda wait function-updated --function-name '<< parameters.function-name >>'
 
@@ -522,9 +555,9 @@ jobs:
           for: << parameters.for >>
       - checkout
       - aws-cli/setup:
-          aws-access-key-id: << parameters.aws-access-key-id >>
-          aws-secret-access-key: << parameters.aws-secret-access-key >>
-          aws-region: << parameters.aws-region >>
+          aws_access_key_id: << parameters.aws-access-key-id >>
+          aws_secret_access_key: << parameters.aws-secret-access-key >>
+          region: << parameters.aws-region >>
       - run:
           name: Setup common environment variables
           command: |
@@ -652,9 +685,9 @@ jobs:
           condition: << parameters.s3-bucket >>
           steps:
             - aws-cli/setup:
-                aws-access-key-id: << parameters.aws-access-key-id >>
-                aws-secret-access-key: << parameters.aws-secret-access-key >>
-                aws-region: << parameters.aws-region >>
+                aws_access_key_id: << parameters.aws-access-key-id >>
+                aws_secret_access_key: << parameters.aws-secret-access-key >>
+                region: << parameters.aws-region >>
             - run:
                 name: Upload Package
                 command: |
