fix(ci): building before tests

diff --git a/.circleci/common.yml b/.circleci/common.yml
--- a/.circleci/common.yml
+++ b/.circleci/common.yml
@@ -2,7 +2,7 @@ version: 2.1
 
 orbs:
   pocket: pocket/circleci-orbs@2.2.0
-  aws-cli: circleci/aws-cli@1.2.1
+  aws-cli: circleci/aws-cli@2.0.6
   aws-ecr: circleci/aws-ecr@7.3.0
 
 commands:
@@ -19,6 +19,7 @@ commands:
             pnpm install
 
 jobs:
+
   test_integrations:
     description: Run integration tests against external services, e.g. MySQL
     parameters:
@@ -59,9 +60,8 @@ jobs:
         description: 'AWS access key id environment variable'
         type: string
       aws-region:
-        description: 'AWS region environment variable'
+        description: 'AWS region value'
         type: string
-        default: AWS_DEFAULT_REGION
       aws-secret-access-key:
         description: 'AWS secret access key environment variable'
         type: string
@@ -84,10 +84,6 @@ jobs:
         description: 'Extra flags to pass to docker build. For examples, see https://docs.docker.com/engine/reference/commandline/build'
         type: string
         default: --build-arg GIT_SHA=${CIRCLE_SHA1}
-      path:
-        description: 'Path to the directory containing your Dockerfile and build context. Defaults to . (working directory).'
-        type: string
-        default: /tmp/workspace/app_prod
       push:
         description: 'Whether or not to push the code'
         type: boolean
@@ -99,78 +95,69 @@ jobs:
         description: 'The docker tag name'
         type: string
         default: latest,$CIRCLE_SHA1
-      remote-docker-layer-caching:
-        type: boolean
-        default: true
-        description: >
-          Enable Docker layer caching if using remote Docker engine.
-          Defaults to false.
 
     executor: aws-cli/default
 
     steps:
       - checkout
-      # - aws-cli/setup:
-      #     aws-access-key-id: << parameters.aws-access-key-id >>
-      #     aws-secret-access-key: << parameters.aws-secret-access-key >>
-      #     aws-region: << parameters.aws-region >>
+      - aws-cli/setup:
+          aws-access-key-id: << parameters.aws-access-key-id >>
+          aws-secret-access-key: << parameters.aws-secret-access-key >>
+          aws-region: << parameters.aws-region >>
       - run:
           name: Setup common environment variables
           command: |
             { \
               echo 'export AWS_ECR_ACCOUNT_URL="<< parameters.ecr-url >>"'; \
-              echo 'export AWS_REGION="$<< parameters.aws-region >>"'; \
               echo 'export REPO_NAME="<< parameters.repo-name >>"'; \
               echo 'export CODEBUILD_PROJECT_NAME="<< parameters.codebuild-project-name >>"'; \
               echo 'export CODEBUILD_PROJECT_BRANCH="<< parameters.codebuild-project-branch >>"'; \
             } >> "$BASH_ENV"
-      # - when:
-      #     condition: <<parameters.push>>
-      #     steps:
-      #       - run:
-      #           name: Docker build/push
-      #           command: |
-      #             #!/bin/bash
-      #             GET_ECR=$(aws ecr describe-repositories --repository-names "${REPO_NAME}" || true)
-      #             # If the ECR does not exist, run the code build project to create it
-      #             if [ -z "$GET_ECR" ]; then
-      #               echo -e "Starting CodeBuild for ${CODEBUILD_PROJECT_NAME}.\n"
-      #               BUILD_ID=$(aws codebuild start-build --project-name "${CODEBUILD_PROJECT_NAME}" --environment-variables-override name=GIT_BRANCH,value="${CODEBUILD_PROJECT_BRANCH}" --source-version "${CODEBUILD_PROJECT_BRANCH}" --query 'build.id' --output text)
-      #               BUILD_STATUS="IN_PROGRESS"
+      - when:
+          condition: <<parameters.push>>
+          steps:
+            - run:
+                name: Docker build/push
+                command: |
+                  #!/bin/bash
+                  GET_ECR=$(aws ecr describe-repositories --repository-names "${REPO_NAME}" || true)
+                  # If the ECR does not exist, run the code build project to create it
+                  if [ -z "$GET_ECR" ]; then
+                    echo -e "Starting CodeBuild for ${CODEBUILD_PROJECT_NAME}.\n"
+                    BUILD_ID=$(aws codebuild start-build --project-name "${CODEBUILD_PROJECT_NAME}" --environment-variables-override name=GIT_BRANCH,value="${CODEBUILD_PROJECT_BRANCH}" --source-version "${CODEBUILD_PROJECT_BRANCH}" --query 'build.id' --output text)
+                    BUILD_STATUS="IN_PROGRESS"
 
-      #               # Wait for the CodeBuild to complete.
-      #               while [ "$BUILD_STATUS" == "IN_PROGRESS" ]; do
-      #                 sleep 10
-      #                 echo "Checking build status"
-      #                 BUILD_STATUS=$(aws codebuild batch-get-builds --ids "$BUILD_ID" --query 'builds[0].buildStatus' --output text)
-      #                 if [ "$BUILD_STATUS" == "IN_PROGRESS" ]; then
-      #                   echo -e "Build is ${BUILD_STATUS}, waiting for build to complete...waiting for 10 seconds before next check...\n"
-      #                 fi
-      #               done
+                    # Wait for the CodeBuild to complete.
+                    while [ "$BUILD_STATUS" == "IN_PROGRESS" ]; do
+                      sleep 10
+                      echo "Checking build status"
+                      BUILD_STATUS=$(aws codebuild batch-get-builds --ids "$BUILD_ID" --query 'builds[0].buildStatus' --output text)
+                      if [ "$BUILD_STATUS" == "IN_PROGRESS" ]; then
+                        echo -e "Build is ${BUILD_STATUS}, waiting for build to complete...waiting for 10 seconds before next check...\n"
+                      fi
+                    done
 
-      #               if [ "$BUILD_STATUS" != "SUCCEEDED" ]; then
-      #                 echo "CodeBuild failed to succeed with status ${BUILD_STATUS}"
-      #                 exit 1
-      #               else
-      #                 echo -e "CodeBuild succeeded\n"
-      #               fi
-      #             fi
-            # - aws-ecr/build-and-push-image:
-            #     checkout: false
-            #     repo: << parameters.repo-name >>
-            #     setup-remote-docker: true
-            #     remote-docker-version: <<parameters.remote-docker-version>>
-            #     remote-docker-layer-caching: <<parameters.remote-docker-layer-caching>>
-            #     path: << parameters.path >>
-            #     aws-access-key-id: << parameters.aws-access-key-id >>
-            #     aws-secret-access-key: << parameters.aws-secret-access-key >>
-            #     tag: << parameters.tag >>
-            #     extra-build-args: << parameters.extra-build-args >>
+                    if [ "$BUILD_STATUS" != "SUCCEEDED" ]; then
+                      echo "CodeBuild failed to succeed with status ${BUILD_STATUS}"
+                      exit 1
+                    else
+                      echo -e "CodeBuild succeeded\n"
+                    fi
+                  fi
+            - aws-ecr/build-and-push-image:
+                checkout: false
+                repo: << parameters.repo-name >>
+                setup-remote-docker: true
+                remote-docker-layer-caching: true
+                aws-access-key-id: << parameters.aws-access-key-id >>
+                aws-secret-access-key: << parameters.aws-secret-access-key >>
+                tag: << parameters.tag >>
+                extra-build-args: << parameters.extra-build-args >>
       - unless:
           condition: <<parameters.push>>
           steps:
             - setup_remote_docker:
-                docker_layer_caching: <<parameters.remote-docker-layer-caching>>
+                docker-layer-caching: true
             - aws-ecr/build-image:
                 repo: << parameters.repo-name >>
                 tag: << parameters.tag >>
